name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
