name: Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Lint
        run: pnpm run lint

#      - name: Test
#        run: pnpm run test

#      - name: Test Coverage
#        run: pnpm run coverage
#
#      - name: Save coverage result
#        uses: actions/upload-artifact@v3
#        with:
#          name: coverage
#          path: ./coverage

      - name: Build
        run: pnpm run build

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  publish:
    name: Publish to Docker Hub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: bkisly32/alleycatapp-client

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
